name: uas_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  flutter:
    sdk: flutter
  flutter_circular_slider: ^2.5.0
  get: 4.6.5
  google_nav_bar: ^5.0.6
  google_sign_in: ^5.4.2
  provider: ^6.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
